backend:
  name: github
  branch: main
  repo: madoozz/madooz-site

media_folder: "public/images/uploads"
collections:
  - name: "pages" # Used in routes, e.g., /admin/collections/pages
    label: "Pages"
    folder: "content/pages" # The path to the folder where the documents are stored
    create: true
    editor:
      preview: false
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - { label: "Page Title", name: "title", widget: "string" }
      - { label: "Hero Title", name: "heroTitle", widget: "string" }
      - { label: "Hero Subtitle", name: "heroSubtitle", widget: "string" }
      - label: "Technologies"
        name: "technologies"
        collapsed: true
        widget: "list"
        fields:
          - { label: Logo image, name: logo, widget: image }

      - { label: "Services Title", name: "serviceTitle", widget: "string" }
      - { label: "Services Subtitle", name: "serviceSubtitle", widget: "string" }
      - label: "Services"
        name: "services"
        collapsed: true
        widget: "list"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: text }
          - { label: Image, name: image, widget: image }

      - { label: "Projects Title", name: "projectTitle", widget: "string" }
      - { label: "Projects Subtitle", name: "projectSubtitle", widget: "string" }
      - label: "Projects"
        name: "projects"
        collapsed: true
        widget: "list"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: text }
          - { label: Image, name: image, widget: image }
          - { label: Link, name: link, widget: string }

      - { label: "Features Title", name: "featureTitle", widget: "string" }
      - { label: "Services Subtitle", name: "featureSubtitle", widget: "string" }
      - label: "Features"
        name: "features"
        collapsed: true
        widget: "list"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: text }
          - {
              label: Icon,
              name: icon,
              widget: image,
              hint: "Recommend to use 64px .png icon at https://www.iconfinder.com/. You can also change the icon color there.",
            }

      - { label: "Testimonial Title", name: "testimonialTitle", widget: "string" }
      - { label: "Testimonial Subtitle", name: "testimonialSubtitle", widget: "string" }
      - label: "Testimonials"
        name: "testimonials"
        collapsed: true
        widget: "list"
        fields:
          - { label: Quote, name: quote, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: Author Jobtitle, name: authorJobtitle, widget: string }
          - { label: Author Image, name: authorImage, widget: image }

      - { label: "Team Title", name: "teamTitle", widget: "string" }
      - { label: "Team Subtitle", name: "teamSubtitle", widget: "string" }
      - label: "Staffs"
        name: "staffs"
        collapsed: true
        widget: "list"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Jobtitle, name: jobtitle, widget: string }
          - { label: About, name: about, widget: text }
          - { label: Avatar, name: avatar, widget: image }
          - { label: Github, name: github, widget: string, required: false }
          - { label: LinkedIn, name: linkedin, widget: string, required: false }
          - { label: Twitter, name: twitter, widget: string, required: false }
